version: '3.9'

services:
  app:
    container_name: nodejs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
    env_file:
      - .env
